### ISSUE TITLE
Maybe check in the plain text ruleset file?

### ISSUE THREAD

**Issue by rmcdouga** [solowargamer/NemosWarHelper#1]
Sorry if I am jumping the gun a little, but I am following your efforts closely.  I think this is a great idea and am thinking of ways to help out.

It looks like you're checking in the .js and .json results of having converted a plain text ruleset file.  It might be helpful to check in the original ruleset file as well, so that people (like myself) could make pull requests to enhance it.

Maybe you could start a separate project which is just a collection of the ruleset files.  People could submit pull requests to improve existing files and/or add new ruleset files for more games.  It would be nice to have a central location to look for (and maintain) ruleset files.  (I'm thinking of doing a ruleset file for Eldritch Horror and maybe Gloomhaven).

Just some thoughts.  Thanks for taking the time to develop this and make the videos.  The possibilities of this project are really exciting.

**Comment by solowargamer** [comment]
Hi McDouga, thanks for your comments.  Nemo's War was just straight code, and didn't use my framework.  I do however have a completed framework check-in (including rule set) on the Cataclysm tree.  Since that's now officially on Amazon and Google, I've checked the code in.

Thanks again for your interest in the project, I look forward to seeing your creations!
